# Site settings
# Enter your own credentials here
title: "Extract Microstructure-Property-Process linkages in aging of Al6061 aluminum alloy"
email: alikhosravani@gmail.com
description: >
  find microstructure-Property-Process relations in aging of Al6061 alloy during which grain structure, texture, and precipitate structure evolve.
baseurl: "/MIC-Al6061-NIST-project" # replace ``/research-pages`` with the name of the parents repository
url: "alikhosravani" # replate ``Materials-Informatics-Lab`` with your Github username
twitter_username: twitterhandle
disqus: tonyfast

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5


gh:
  user: alikhosravani
  repo: Al6061-NIST-project
  # Branch hosting Github pages
  branch: gh-pages
